# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/UQDialog.ui'
#
# Created: Sun Dec 20 22:15:34 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 366)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.kodeLabel = QtGui.QLabel(self.frame)
        self.kodeLabel.setObjectName("kodeLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.kodeLabel)
        self.kodeLineEdit = QtGui.QLineEdit(self.frame)
        self.kodeLineEdit.setObjectName("kodeLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.kodeLineEdit)
        self.namaLabel = QtGui.QLabel(self.frame)
        self.namaLabel.setObjectName("namaLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.namaLabel)
        self.namaLineEdit = QtGui.QLineEdit(self.frame)
        self.namaLineEdit.setObjectName("namaLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.namaLineEdit)
        self.tempatLahirLabel = QtGui.QLabel(self.frame)
        self.tempatLahirLabel.setObjectName("tempatLahirLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.tempatLahirLabel)
        self.tempatLahirLineEdit = QtGui.QLineEdit(self.frame)
        self.tempatLahirLineEdit.setObjectName("tempatLahirLineEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.tempatLahirLineEdit)
        self.tanggalLahirLabel = QtGui.QLabel(self.frame)
        self.tanggalLahirLabel.setObjectName("tanggalLahirLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.tanggalLahirLabel)
        self.tanggalLahirDateEdit = QtGui.QDateEdit(self.frame)
        self.tanggalLahirDateEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tanggalLahirDateEdit.setCalendarPopup(True)
        self.tanggalLahirDateEdit.setObjectName("tanggalLahirDateEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.tanggalLahirDateEdit)
        self.jenisKelaminLabel = QtGui.QLabel(self.frame)
        self.jenisKelaminLabel.setObjectName("jenisKelaminLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.jenisKelaminLabel)
        self.jenisKelaminComboBox = QtGui.QComboBox(self.frame)
        self.jenisKelaminComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.jenisKelaminComboBox.setObjectName("jenisKelaminComboBox")
        self.jenisKelaminComboBox.addItem("")
        self.jenisKelaminComboBox.addItem("")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.jenisKelaminComboBox)
        self.handphoneLabel = QtGui.QLabel(self.frame)
        self.handphoneLabel.setObjectName("handphoneLabel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.handphoneLabel)
        self.handphoneLineEdit = QtGui.QLineEdit(self.frame)
        self.handphoneLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Indonesian, QtCore.QLocale.Indonesia))
        self.handphoneLineEdit.setObjectName("handphoneLineEdit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.handphoneLineEdit)
        self.alamatLabel = QtGui.QLabel(self.frame)
        self.alamatLabel.setObjectName("alamatLabel")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.alamatLabel)
        self.alamatTextEdit = QtGui.QTextEdit(self.frame)
        self.alamatTextEdit.setTabChangesFocus(True)
        self.alamatTextEdit.setObjectName("alamatTextEdit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.alamatTextEdit)
        self.statusCheckBox = QtGui.QCheckBox(self.frame)
        self.statusCheckBox.setObjectName("statusCheckBox")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.statusCheckBox)
        self.verticalLayout.addWidget(self.frame)
        self.statusAction = QtGui.QLabel(Dialog)
        self.statusAction.setText("")
        self.statusAction.setObjectName("statusAction")
        self.verticalLayout.addWidget(self.statusAction)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deletePushButton = QtGui.QPushButton(Dialog)
        self.deletePushButton.setObjectName("deletePushButton")
        self.horizontalLayout.addWidget(self.deletePushButton)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.actionValidasi = QtGui.QAction(Dialog)
        self.actionValidasi.setObjectName("actionValidasi")
        self.kodeLabel.setBuddy(self.kodeLineEdit)
        self.namaLabel.setBuddy(self.namaLineEdit)
        self.tempatLahirLabel.setBuddy(self.tempatLahirLineEdit)
        self.tanggalLahirLabel.setBuddy(self.tanggalLahirDateEdit)
        self.jenisKelaminLabel.setBuddy(self.jenisKelaminComboBox)
        self.handphoneLabel.setBuddy(self.handphoneLineEdit)
        self.alamatLabel.setBuddy(self.alamatTextEdit)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.kodeLineEdit, self.namaLineEdit)
        Dialog.setTabOrder(self.namaLineEdit, self.tempatLahirLineEdit)
        Dialog.setTabOrder(self.tempatLahirLineEdit, self.tanggalLahirDateEdit)
        Dialog.setTabOrder(self.tanggalLahirDateEdit, self.jenisKelaminComboBox)
        Dialog.setTabOrder(self.jenisKelaminComboBox, self.handphoneLineEdit)
        Dialog.setTabOrder(self.handphoneLineEdit, self.alamatTextEdit)
        Dialog.setTabOrder(self.alamatTextEdit, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.kodeLabel.setText(QtGui.QApplication.translate("Dialog", "&Kode :", None, QtGui.QApplication.UnicodeUTF8))
        self.kodeLineEdit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Kode", None, QtGui.QApplication.UnicodeUTF8))
        self.namaLabel.setText(QtGui.QApplication.translate("Dialog", "&Nama :", None, QtGui.QApplication.UnicodeUTF8))
        self.namaLineEdit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Nama", None, QtGui.QApplication.UnicodeUTF8))
        self.tempatLahirLabel.setText(QtGui.QApplication.translate("Dialog", "Tempa&t Lahir :", None, QtGui.QApplication.UnicodeUTF8))
        self.tempatLahirLineEdit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Tempat Lahir", None, QtGui.QApplication.UnicodeUTF8))
        self.tanggalLahirLabel.setText(QtGui.QApplication.translate("Dialog", "Tan&ggal Lahir :", None, QtGui.QApplication.UnicodeUTF8))
        self.tanggalLahirDateEdit.setDisplayFormat(QtGui.QApplication.translate("Dialog", "dd-MM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.jenisKelaminLabel.setText(QtGui.QApplication.translate("Dialog", "Jenis &Kelamin :", None, QtGui.QApplication.UnicodeUTF8))
        self.jenisKelaminComboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "Laki - Laki", None, QtGui.QApplication.UnicodeUTF8))
        self.jenisKelaminComboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "Perempuan", None, QtGui.QApplication.UnicodeUTF8))
        self.handphoneLabel.setText(QtGui.QApplication.translate("Dialog", "&Handphone :", None, QtGui.QApplication.UnicodeUTF8))
        self.handphoneLineEdit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Handphone", None, QtGui.QApplication.UnicodeUTF8))
        self.alamatLabel.setText(QtGui.QApplication.translate("Dialog", "&Alamat :", None, QtGui.QApplication.UnicodeUTF8))
        self.alamatTextEdit.setStatusTip(QtGui.QApplication.translate("Dialog", "Alamat", None, QtGui.QApplication.UnicodeUTF8))
        self.alamatTextEdit.setWhatsThis(QtGui.QApplication.translate("Dialog", "Alamat", None, QtGui.QApplication.UnicodeUTF8))
        self.statusCheckBox.setText(QtGui.QApplication.translate("Dialog", "Aktif", None, QtGui.QApplication.UnicodeUTF8))
        self.deletePushButton.setText(QtGui.QApplication.translate("Dialog", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionValidasi.setText(QtGui.QApplication.translate("Dialog", "Validasi", None, QtGui.QApplication.UnicodeUTF8))

